query GetAboutPage {
  aboutPage(
    where: {
      title: "About me"
    }
  ) {
    ...AboutPageMainFields
  }
}

fragment AboutPageMainFields on AboutPage {
  id
  pageHero {
    mainHeading
    showcaseImage {
      url
    }
    introSubheading {
      html
    }
  }
  servicesList(first: 12) {
    title
    portfolioCategory {
      id
      name
    }
  }
  processTitle
  myProcessSection(first: 9) {
    id
    name
    icon {
      url
      fileName
    }
    content {
      html
    }
  }
  contactSectionTitle
  pageContactSection {
    id
    title
    link
    file {
      fileName
      url
    }
    icon {
      url
      fileName
    }
    isExternal
  }
}
