query GetAboutPage {
  aboutPage(where: {title: "About me"}) {
    ...AboutPageMainFields
  }
}

fragment AboutPageMainFields on AboutPage {
  id
  myProcess {
    showList
    title
    image {
      url
      fileName
    }
  }
  pageHero {
    mainHeading
    showcaseImage {
      url
    }
    introSubheading {
      html
    }
  }
  myProcessSection {
    id
    name
    icon {
      url
      fileName
    }
    content {
      html
    }
  }
  contactSectionTitle
  pageContactSection {
    id
    title
    link
    file {
      fileName
      url
    }
    icon {
      url
      fileName
    }
    isExternal
  }
}
