query GetHomepage {
  homepage(
    where: {title: "Homepage"}
    stage: PUBLISHED
) {
    ...HomepageFragmentFields
  }
}

fragment HomepageFragmentFields on Homepage {
  slug
  title
  variant
  bannerImage {
    url
  }
  general {
    mainHeading
    introSubheading {
      html
    }
    showcaseImage {
      url
      fileName
    }
  }
  services {
    id
    showListOfServices
    title
  }
}
