query GetAllPortfolios {
  portfolios(
  orderBy: createdAt_ASC
  stage: PUBLISHED
) {
    ...PortfolioFragmentFields
  }
}

query GetPortfoliosByCategory(
  $portfolioCategory: String!
) {
  portfolios(
    where:{ portfolioCategory: { name: $portfolioCategory}},
    stage: PUBLISHED
    orderBy: createdAt_ASC
  ) {
    ...PortfolioFragmentFields
  }
}

query GetPortfolioCategories {
  portfolioCategories(
  stage: PUBLISHED
) {
    id
    name
  }
}


fragment PortfolioFragmentFields on Portfolio {
  id
  slug
  title
  updatedAt
  year
  showcaseImage {
    id
    fileName
    url
  }
  portfolioCategory {
    id
    name
  }
}
