query GetAllPortfolios {
  portfolios(
  orderBy: createdAt_ASC
  stage: PUBLISHED
) {
    ...PortfolioFragmentFields
  }
}

query GetPortfolioCategories {
  portfolioCategories(
  first: 2
  stage: PUBLISHED
) {
    id
    name
  }
}

query GetPortfoliosByCategoryName(
  $category: String!
) {
  portfolios(
    where: {portfolioCategories_some: {name: $category}}
) {
    portfolioCategories {
      name
    }
    title
    slug
  }
}

fragment PortfolioFragmentFields on Portfolio {
  id
  slug
  title
  updatedAt
  year
  shortHeading
  showcaseImage {
    id
    fileName
    url
  }
  portfolioCategories {
    id
    name
  }
}
