query GetAllProcess {
  processes(
  stage: PUBLISHED
) {
    ...ProcessFragmentFields
  }
}

query GetMyProcessSection {
  myProcessSection(where: { title: "My Process" }) {
    title
    showList
    image {
      url
    }
  }
}

fragment ProcessFragmentFields on Process {
  id
  name
  content {
    html
  }
  icon {
    fileName
    url
  }
}
